<template>
    <div id="about_source">
            <h3>About this page <span class='x' v-on:click="hideAbout()">&nbsp;</span></h3>
            <p>This page summarizes currently available 3D structural information for all proteins believed to comprise COVID-19 (also known as Human SARS coronavirus 2, SARS-CoV-2).</p>
            <p>For each protein, structural models were generated by finding all sequence regions with detectable similarity to any currently published 3D structure (in the <a href="https://www.wwpdb.org/">PDB</a>), based on a systematic, machine-learning search method (<a href="https://www.nature.com/articles/nmeth.3258">O'Donoghue et al., Nature Methods 2015</a>).</p>
            <p>For proteins with at least one match structure, an image of the best match (based on sequence identity) is shown.</p>
            <p>Click on an image to access all matching structures for that protein, and to overlay sequence features (e.g., domains, SNPs, PTMs).</p>
            <p>Proteins with no matching structure have no detectable sequence homology to any experimentally-determined 3D structure currently published (in the <a href="https://www.wwpdb.org/">PDB</a>). However, as new structures become publicly available, they will be added to this page.</p>
          </div>
</template>

<script>
import store from '@/store/index'
import $ from 'jquery'

export default {
  name: 'AboutSource',
  computed: {
    data () {
      return store.state.message
    }
  },
  methods: {
    hideAbout: function () {
    // dim background
      $('div#about_source, div#help_overlay').hide()
      $('div.dimmer').remove()
      $('div#about_source').hide()
    }
  },
  mounted () {
    var Position = window.innerWidth / 2 - $('#about_source').width() / 2
    Position = Position + 'px'
    $('#about_source').css({
      left: Position
    })
  }
}
</script>

<style scoped>
#about_source{
    display: none;
    height: fit-content;
    border-radius: 12px;
    position: fixed;
    top: 1em;
    left: 10%;
    max-width: 700px;
    width: 80%;
    padding: 2px;
    margin: 10px auto;
    background-color: #DDD;
    z-index: 105;
    /* bottom: 1em; */
    overflow: scroll;
    font-size: 10px;
}
#about_source h3{
    background-color: #999;
    border-radius: 10px;
    color: white;
    font-size: 100%;
    font-weight: normal;
    letter-spacing: 0.2em;
    text-transform: uppercase;
    padding: 2px 3px 2px 10px;
    margin: 0px;
}
@media screen and (min-width: 320px) {
      #about_source {
        font-size: calc(8px + 6 * ((100vw - 320px) / 680));
      }
  }
  @media screen and (min-width: 1000px) {
      #about_source {
        font-size: 16px;
      }
  }

p {
  text-align: left;
  margin: 1em;
}
</style>
