<template>
    <div id="about_matrix">
        <div id="title_0" v-if="$mq === 'laptop'">
            <span id="Orgname_0">Structural models of {{ OrganismName }} proteins&nbsp;</span>
            <span id="matches_0"></span>
            <span id="help" @mouseover="showAbout()" v-if="$mq === 'laptop'">?</span>
        </div>
        <div id="title_0" v-if="$mq === 'mobile' || $mq === 'tablet'" @mousedown="showAboutPhone()">
            <span id="Orgname_0">Structural models of {{ OrganismName }} proteins&nbsp;</span>
            <span id="matches_0"></span>
            <span id="help">?</span>
        </div>
        <div id="content">
            <div id="title">
                <span id="Orgname">Structural models of {{ OrganismName }} proteins&nbsp;</span>
                <span id="matches"></span>
                <span id="close" @click="hideAbout()">✕</span>
            </div>
            <p>This page summarizes currently available 3D structural information for all proteins believed to comprise
              <a v-bind:href="redirect(this.synonymsArray[0])" target="_blank"> {{ OrganismName }} </a>
              (a.k.a. {{ this.synonymsString }} ).
            </p>
            <p>For each protein, structural models were generated by finding all sequence regions with detectable similarity to any currently published 3D structure (in the <a href="https://www.wwpdb.org/">PDB</a>), based on a systematic, machine-learning search method (<a href="https://www.nature.com/articles/nmeth.3258">O'Donoghue et al., Nature Methods 2015</a>).</p>
            <p>For proteins with at least one match structure, an image of the best match (based on sequence identity) is shown.</p>
            <p>Click on an image to access all matching structures for that protein, and to overlay sequence features (e.g., domains, SNPs, PTMs).</p>
            <p>Proteins with no matching structure have no detectable sequence homology to any experimentally-determined 3D structure currently published (in the <a href="https://www.wwpdb.org/">PDB</a>). However, as new structures become publicly available, they will be added to this page.</p>
        </div>
    </div>
</template>

<script>
import store from '@/store/index'

export default {
  name: 'AboutMatrix',
  computed: {
    data () {
      return store.state.message
    }
  },
  data () {
    return {
      synonymsString: null,
      synonymsArray: null
    }
  },
  beforeMount () {
    this.synonymsArray = this.OrgSynonyms.split(',')
    this.synonymsString = this.synonymsArray[1]
    for (var i = 2; i < this.synonymsArray.length; i++) {
      this.synonymsString = this.synonymsString + ', ' + this.synonymsArray[i]
    }
  },
  props: ['OrganismName', 'OrgSynonyms', 'checkDevice'],
  methods: {
    hideAbout: function () {
      document.querySelector('#content').style.visibility = 'hidden'
      document.querySelector('div.dimmer').remove()
      setTimeout(function () { document.querySelector('#help').style.pointerEvents = 'auto' }, 1000)
      document.querySelector('#help').style.pointerEvents = 'none'
    },
    showAbout: function () {
      document.querySelector('#content').style.visibility = 'visible'
      if (document.getElementsByClassName('dimmer').length === 0) {
        var elemDiv = document.createElement('div')
        elemDiv.className = 'dimmer'
        document.body.append(elemDiv)
        document.querySelector('#content').style.visibility = 'visible'

        document.querySelector('div.dimmer').addEventListener('mouseover', function () {
          document.querySelector('#content').style.visibility = 'hidden'
          document.querySelector('div.dimmer').remove()
        })
      } else {
        document.querySelector('div.dimmer').remove()
      }
    },
    showAboutPhone: function () {
      document.querySelector('#content').style.visibility = 'visible'
      if (document.getElementsByClassName('dimmer').length === 0) {
        var elemDiv = document.createElement('div')
        elemDiv.className = 'dimmer'
        document.body.append(elemDiv)
        document.querySelector('#content').style.visibility = 'visible'

        document.querySelector('div.dimmer').addEventListener('click', function () {
          document.querySelector('#content').style.visibility = 'hidden'
          document.querySelector('div.dimmer').remove()
        })
      } else {
        document.querySelector('div.dimmer').remove()
      }
    },
    redirect: function (OrganismID) {
      var url = 'https://www.uniprot.org/taxonomy/' + OrganismID
      return (url)
    }
  }
}
</script>

<style scoped>

#about_matrix{
    margin-left: 12px;
    margin-top: 15px;
    margin-bottom: 20px;
}

@media only screen
  and (min-width : 100px)
  and (max-width : 700px) {
    #about_matrix{
    margin-left: calc(32px + 0.8vw);
  }
}

#title, #title_0{
    display: inline-flex;
    align-items: baseline;
    border-radius: 5em;
    background: #999999;
    padding: 5px calc(9px + 0.4vw);
}

#content {
    position: absolute;
    z-index: 4;
    visibility: hidden;
    border-radius: 2em;
    background: #DEDEDE;
    top: 10px;
    left: 33%;
    right: 33%;
    padding: 8px calc(10px + 0.4vw) 20px calc(10px + 0.4vw);
    width: 34%;
    max-height: 90vh;
    overflow: auto;
}
#content p {
    text-align: left;
    width: 90%;
    margin: 0.8em auto;
    line-height: 1.65em;
}
#Orgname, #Orgname_0 {
    color: #fff;
    font-size: calc(8px + 0.8vw);
    font-weight: 700;
}

#matches, #matches_0 {
    font-size: calc(10px + 0.4vw);
}

#help, #close {
    border-radius: 50%;
    background-color: #f0f8ff;
    width: calc(10px + .8vw);
    height: calc(10px + .8vw);
    font-size: calc(10px + .4vw);
    margin: 0px 0px 0px 5px;
    line-height: calc(10px + 1vw);
}

#close:hover, #help:hover {
  background-color:#E9A45B;
  color: white;
  cursor: pointer;
}

/* iPhone SE */
@media only screen
  and (min-width : 200px)
  and (max-height : 600px) {
  #Orgname{
    font-size: calc(7px + 1vw);
  }
  #matches {
    font-size: calc(7px + 0.5vw);
  }
  #title_0 {
    padding: 5px calc(3px + 0.4vw);
  }
  #title{
    padding: 5px calc(9px + 0.4);
  }
  #content{
    left: 5%;
    right: 5%;
    width: 90%;
  }
  #about_matrix{
    margin-bottom: 15px;
  }
}

/* Tall aspect ratio */
    @media (max-aspect-ratio: 3/4) {
        #content{
            font-size: 10px;
            left: 5%;
            right: 5%;
            width: 90%;
        }
    }
    @media (max-aspect-ratio: 3/4) and (min-height: 1000px) {
        #content{
            font-size: 12px;
        }
    }
    @media screen and (min-width: 320px) {
      #content {
          /* font-size: calc(8px + 7 * ((100vw - 320px) / 680)); */
          font-size: calc(9px + 0.5vw);
      }
    }
    @media screen and (min-width: 1000px) {
        #content {
            font-size: 16px;
        }
    }
    @media (min-width: 590px) and (max-width: 1000px) {
        #content{
            font-size: calc(8px + 0.8vw);
            left: 25%;
            right: 25%;
            width: 50%;
        }
    }
</style>
