<template>
    <div id="about_matrix">
        <div id="title_0">
            <a title='Watch the introductory video' v-bind:href="'https://youtu.be/J2nWQTlJNaY'" target="_blank"><img @mouseover="activatePlay(0)" @mouseleave="resetPlay(0)" class='icon' id='play' v-bind:src="'/images/Play.png'"/></a>
            <span id="Orgname_0" @mouseover="activateHelp" @mouseleave="resetOver" v-if="$mq === 'mobile'">{{ OrganismName }} PROTEIN STRUCTURES&nbsp;</span>
            <span id="Orgname_0" @mouseover="activateHelp" @mouseleave="resetOver" v-if="$mq === 'laptop' || $mq === 'tablet'">STRUCTURAL MODELS OF {{ OrganismName }} PROTEINS&nbsp;</span>
            <!-- <span id="matches_0"></span> -->
             <a title="Read our bioRxiv preprint" v-bind:href="'https://doi.org/10.1101/2020.07.16.207308'" target="_blank"><img @mouseover="activatePaper(0)" @mouseleave="resetPaper(0)" class='icon' id='paper' v-bind:src="'/images/Document.png'"/></a>
            <!-- <span id="help" @mouseover="activarOver" @mousedown="showAbout" @mouseleave="resetOver" v-if="$mq === 'laptop'">?</span> -->
            <img class='icon' id='help' @mouseover="activateOver" @click="showAbout" @mouseleave="resetOver" v-bind:src="'/images/Info.png'"/>
        </div>
        <!-- <div id="title_0" v-if="$mq === 'mobile'" @mousedown="showAboutPhone">
            <span id="Orgname_0">{{ OrganismName }} PROTEINS STRUCTURES&nbsp;</span>
            <img class='icon' id='help' @mouseover="activateOver" @click="showAbout" @mouseleave="resetOver" v-bind:src="'/images/Info.png'"/>
        </div> -->
        <div id="content">
            <div id="title">
                <a title='Watch the introductory video' v-bind:href="'https://youtu.be/J2nWQTlJNaY'" target="_blank"><img @mouseover="activatePlay(1)" @mouseleave="resetPlay(1)" class='icon' id='play' v-bind:src="'/images/Play.png'"/></a>
                <span id="Orgname" @mouseover="activateHelp" @mouseleave="resetOver" v-if="$mq === 'mobile'">{{ OrganismName }} PROTEIN STRUCTURES&nbsp;</span>
                <span id="Orgname" @mouseover="activateHelp" @mouseleave="resetOver" v-if="$mq === 'laptop' || $mq === 'tablet'">STRUCTURAL MODELS OF {{ OrganismName }} PROTEINS&nbsp;</span>
                <!-- <span id="matches"></span> -->
                <a title="Read our bioRxiv preprint" v-bind:href="'https://doi.org/10.1101/2020.07.16.207308'" target="_blank"><img @mouseover="activatePaper(1)" @mouseleave="resetPaper(1)" class='icon' id='paper' v-bind:src="'/images/Document.png'"/></a>
                <!-- <span id="close" @click="hideAbout()">✕</span> -->
                <img class='icon' id='close' @mouseover="activateClose(1)" @mouseleave="resetClose(1)" @click="hideAbout()" v-bind:src="'/images/Close.png'"/>
            </div>
            <div>
            <p>This page summarizes currently available 3D structural information for all proteins believed to comprise
              <a v-bind:href="redirect(this.synonymsArray[0])" target="_blank"> {{ OrganismName }} </a>
              (a.k.a. {{ this.synonymsString }} ).
              <br/>
            For each protein, structural models were generated by finding all sequence regions with detectable similarity to any currently published 3D structure (in the <a href="https://www.wwpdb.org/">PDB</a>), based on a systematic, machine-learning search method (<a href="https://www.nature.com/articles/nmeth.3258">O'Donoghue et al., Nature Methods 2015</a>).
            <br/>
            <br/>
            For proteins with at least one match structure, an image of the best match (based on sequence identity) is shown.
            <br/>
            <br/>
            Click on an image to access all matching structures for that protein, and to overlay sequence features (e.g., domains, SNPs, PTMs).
            <br/>
            <br/>
            Proteins with no matching structure have no detectable sequence homology to any experimentally-determined 3D structure currently published (in the <a href="https://www.wwpdb.org/">PDB</a>). However, as new structures become publicly available, they will be added to this page.
            </p>
            <p id='teams'>
              <i>
              The Aquaria-COVID resource is hosted by the Garvan Institute of Medical Research (Sydney, Australia), and is maintained in collaboration with CSIRO Data61 (
              Sydney, Australia), the School of Biotechnology and Biomolecular Sciences at the University of NSW (Sydney, Australia), the Department of Bioengineering Sciences
              at Weihenstephan-Tr. University of Applied Sciences (Freising, Germany), the Department of Informatics, Bioinformatics & Computational Biology at the Technical
              University of Munich (Germany), the School of Life Sciences of the University of Dundee (UK), and the Institute of Structural and Molecular Biology at University College London (UK).
              </i>
            </p>
            </div>
        </div>
    </div>
</template>

<script>
import store from '@/store/index'

export default {
  name: 'AboutMatrix',
  computed: {
    data () {
      return store.state.message
    }
  },
  data () {
    return {
      synonymsString: null,
      synonymsArray: null,
      timer: null
    }
  },
  beforeMount () {
    this.synonymsArray = this.OrgSynonyms.split(',')
    this.synonymsString = this.synonymsArray[1]
    for (var i = 2; i < this.synonymsArray.length; i++) {
      this.synonymsString = this.synonymsString + ', ' + this.synonymsArray[i]
    }
  },
  props: ['OrganismName', 'OrgSynonyms', 'checkDevice'],
  mounted () {
    document.querySelector('img#play').addEventListener('mouseover', function () {
      document.querySelector('img#play').src = '/images/Play_Hover.png'
    })
    document.querySelector('img#play').addEventListener('mouseout', function () {
      document.querySelector('img#play').src = '/images/Play.png'
    })
    document.querySelector('img#paper').addEventListener('mouseover', function () {
      document.querySelector('img#paper').src = '/images/Document_Hover.png'
    })
    document.querySelector('img#paper').addEventListener('mouseout', function () {
      document.querySelector('img#paper').src = '/images/Document.png'
    })
    if (window.location.hash === '#info') {
      this.showAbout()
    }
  },
  methods: {
    activatePlay (n) {
      document.querySelector('#help').src = '/images/Info.png'
      document.querySelectorAll('#play')[n].src = '/images/Play_Hover.png'
      document.querySelectorAll('#play'[n]).style.cursor = 'pointer'
    },
    activatePaper (n) {
      document.querySelector('#help').src = '/images/Info.png'
      document.querySelectorAll('#paper')[n].src = '/images/Document_Hover.png'
      document.querySelectorAll('#paper')[n].style.cursor = 'pointer'
    },
    resetPlay (n) {
      document.querySelectorAll('#play')[n].src = '/images/Play.png'
    },
    resetPaper (n) {
      document.querySelectorAll('#paper')[n].src = '/images/Document.png'
    },
    activateHelp () {
      document.querySelector('#help').src = '/images/Info_Hover.png'
      document.querySelector('#help').style.cursor = 'pointer'
    },
    activateClose () {
      document.querySelector('#close').src = '/images/Close_Hover.png'
      document.querySelector('#close').style.cursor = 'pointer'
    },
    resetClose () {
      document.querySelector('#close').src = '/images/Close.png'
      document.querySelector('#close').style.cursor = 'pointer'
    },
    resetOver () {
      clearTimeout(this.timer)
      document.querySelector('#help').src = '/images/Info.png'
    },
    hideAbout: function () {
      document.querySelector('#content').style.display = 'none'
      document.querySelector('#title_0').style.display = 'inline-table'
      document.querySelector('div.dimmer').remove()
      setTimeout(function () { document.querySelector('#help').style.pointerEvents = 'auto' }, 1000)
      document.querySelector('#help').style.pointerEvents = 'none'
    },
    showAbout: function () {
      document.querySelector('#content').style.display = 'block'
      document.querySelector('#title_0').style.display = 'none'
      if (document.getElementsByClassName('dimmer').length === 0) {
        var elemDiv = document.createElement('div')
        elemDiv.className = 'dimmer'
        document.body.append(elemDiv)
        document.querySelector('#content').style.display = 'block'
        document.querySelector('#title_0').style.display = 'none'

        document.querySelector('div.dimmer').addEventListener('click', function () {
          document.querySelector('#content').style.display = 'none'
          document.querySelector('#title_0').style.display = 'inline-table'
          document.querySelector('div.dimmer').remove()
        })
      } else {
        document.querySelector('div.dimmer').remove()
      }
    },
    showAboutPhone: function () {
      document.querySelector('#content').style.display = 'block'
      if (document.getElementsByClassName('dimmer').length === 0) {
        var elemDiv = document.createElement('div')
        elemDiv.className = 'dimmer'
        document.body.append(elemDiv)
        document.querySelector('#content').style.display = 'block'

        document.querySelector('div.dimmer').addEventListener('click', function () {
          document.querySelector('#content').style.visibility = 'hidden'
          document.querySelector('div.dimmer').remove()
        })
      } else {
        document.querySelector('div.dimmer').remove()
      }
    },
    activateOver () {
      this.timer = setTimeout(function () {
        document.querySelector('#content').style.display = 'block'
        document.querySelector('#title_0').style.display = 'none'
        if (document.getElementsByClassName('dimmer').length === 0) {
          var elemDiv = document.createElement('div')
          elemDiv.className = 'dimmer'
          document.body.append(elemDiv)
          document.querySelector('#content').style.display = 'block'
          document.querySelector('#title_0').style.display = 'none'

          document.querySelector('div.dimmer').addEventListener('click', function () {
            document.querySelector('#content').style.display = 'none'
            document.querySelector('#title_0').style.display = 'inline-table'
            document.querySelector('div.dimmer').remove()
          })
        } else {
          document.querySelector('div.dimmer').remove()
        }
      }, 1000)
      document.querySelector('#help').src = '/images/Info_Hover.png'
      document.querySelector('#help').style.cursor = 'pointer'
    },
    redirect: function (OrganismID) {
      var url = 'https://www.uniprot.org/taxonomy/' + OrganismID
      return (url)
    }
  }
}
</script>

<style scoped>
#help, #close, #paper{
  padding-left: 0px;
}
img.icon{
  height: calc(15px + 0.9vw);
  position: relative;
  top: calc(-1px + 0.001vh)
}
img#play{
    padding-right: 4px;
}
#about_matrix{
    margin-left: 12px;
    margin-top: calc(1px + 1.5vh);
    margin-bottom: 20px;
}

@media only screen
  and (min-width : 100px)
  and (max-width : 700px) {
    #about_matrix{
    margin-left: calc(32px + 0.8vw);
  }
}

#title, #title_0{
    display: inline-table;
    align-items: baseline;
    border-radius: 5em;
    background: #999999;
    padding: 5px calc(4px + 0.4vw)
}

#title{
  margin-top: 7px;
}
#content {
    position: relative;
    z-index: 4;
    display: none;
    border-radius: 2em;
    background: #DEDEDE;
    /* top: 10px;
    left: 33%;
    right: 33%;
    padding: 8px calc(10px + 0.4vw) 20px calc(10px + 0.4vw);
    width: 44%;
    max-height: 90vh;
    overflow: auto; */
}

/* #content {
    position: absolute;
    z-index: 4;
    visibility: hidden;
    border-radius: 2em;
    background: #DEDEDE;
    top: 10px;
    left: 33%;
    right: 33%;
    padding: 8px calc(10px + 0.4vw) 20px calc(10px + 0.4vw);
    width: 44%;
    max-height: 90vh;
    overflow: auto;
} */
#content p {
    text-align: left;
    width: 90%;
    margin: 0.8em auto;
    line-height: 1.65em;
    font-size: calc(8px + 0.6vw);
    padding-bottom: 15px;
}

p#teams{
  font-size: calc(8px + 0.6vw);
  padding-bottom: 20px;
}

#Orgname, #Orgname_0 {
    color: #fff;
    font-size: calc(8px + 0.6vw);
    font-weight: 500;
    vertical-align: middle;
}

#matches, #matches_0 {
    font-size: calc(10px + 0.4vw);
}

/* #help, #close {
    border-radius: 50%;
    background-color: #808080;
    width: calc(10px + .8vw);
    height: calc(10px + .8vw);
    font-size: calc(10px + .4vw);
    margin: 0px 0px 0px 4px;
    line-height: calc(11px + 1vw);
    color: #999999;
    font-weight: 900;
} */

/* #close:hover, #help:hover {
  background-color:#bebebe;
  color: #fe941a;
  cursor: pointer;
} */

/* iPhone SE */
/* @media only screen
  and (min-width : 200px)
  and (max-height : 600px) { */
  /* #Orgname, #Orgname_0 {
    color: #fff;
    font-size: calc(6px + 0.8vw);
    font-weight: 500;
}
  #matches {
    font-size: calc(7px + 0.5vw);
  }
  #title_0 {
    padding: 5px calc(3px + 0.4vw);
  }
  #title{
    padding: 5px calc(9px + 0.4);
  } */
  /* #content{
    left: 5%;
    right: 5%;
    width: 90%;
  } */
  /* #about_matrix{
    margin-bottom: 15px;
  }
} */

@media all and (max-width: 280px) {
  #content{
    right: 18%;
    width: 122%;
  }
  #Orgname, #Orgname_0 {
    color: #fff;
    font-size: calc(8px);
    font-weight: 500;
    vertical-align: middle;
  }
}

@media all and (max-width: 535px) and (min-width: 281px) and (max-height: 640px) {
  #content {
    right: 16%;
    width: 121%;
  }
}

@media all and (min-width: 281px) and (max-width: 535px) and (min-height: 641px) {
  #content{
    right: 10%;
    width: 108%;
  }
      font-size: calc(8px + 0.6vw);

}

@media all and (min-width: 375px) and (max-width: 535px) {
  #content{
    /* left: 0%;
    width: 90%; */
    left: -8%;
    width: 106%;
  }
}

@media all and (min-width: 425px) and (max-width: 449px) {
  #content{
    left: 8%;
    width: 78%;
  }
}
@media all and (min-width: 450px) and (max-width: 535px) {
  #content{
    left: 0%;
    width: 92%;
  }
}

@media all and (min-width: 535px) and (max-width: 550px) {
  #content{
    left: 7%;
    width: 81%;
    /* left: 17%;
    width: 63%; */
  }
}
@media all and (min-width: 550px) and (max-width: 706px) {
  #content{
    left: 8%;
    width: 77%;
  }
}

@media all and (min-width: 706px) and (max-width: 811px) {
  #content{
    left: 23%;
    width: 58%;
  }
}
@media all and (min-width: 812px) and (max-width: 1000px) {
  #content{
    left: 25%;
    width: 53%;
  }
}
@media all and (min-width: 1000px) and (max-width: 1900px) {
  #content{
    left: 27%;
    width: calc(75vw - 33%)
  }
}

@media all and (min-width: 1900px) and (max-width: 3000px) {
  #content{
    left: 32%;
    width: 35%;
  }
}

@media all and (min-width: 3000px) {
  #content{
    width: calc(56% - 23vw);
    left: calc(22% + 11vw);
  }
}
</style>
