<template>
    <div id="about_matrix">
        <div id="title">
            <p id="Orgname">Structural models of {{ OrganismName }} proteins&nbsp;</p>
            <p id="matches"></p>
            <p id="help" @mouseover="showAbout()">?</p>
            <p id="close" @click="hideAbout()">X</p>
        </div>
        <div id="content">            <!-- if content visible, help mouseover disable -->
            <!-- <span class='x' v-on:click="hideAbout()">&nbsp;</span> -->
            <p>This page summarizes currently available 3D structural information for all proteins believed to comprise {{ OrganismName }} (also known as Human SARS coronavirus 2, SARS-CoV-2).</p>
            <p>For each protein, structural models were generated by finding all sequence regions with detectable similarity to any currently published 3D structure (in the <a href="https://www.wwpdb.org/">PDB</a>), based on a systematic, machine-learning search method (<a href="https://www.nature.com/articles/nmeth.3258">O'Donoghue et al., Nature Methods 2015</a>).</p>
            <p>For proteins with at least one match structure, an image of the best match (based on sequence identity) is shown.</p>
            <p>Click on an image to access all matching structures for that protein, and to overlay sequence features (e.g., domains, SNPs, PTMs).</p>
            <p>Proteins with no matching structure have no detectable sequence homology to any experimentally-determined 3D structure currently published (in the <a href="https://www.wwpdb.org/">PDB</a>). However, as new structures become publicly available, they will be added to this page.</p>
        </div>
    </div>
</template>

<script>
import store from '@/store/index'

export default {
  name: 'AboutMatrix',
  computed: {
    data () {
      return store.state.message
    }
  },
  props: ['OrganismName'],
  methods: {
    hideAbout: function () {
        console.log("THIS ")
      document.querySelector('#content').style.visibility = 'hidden'
      document.querySelector('div.dimmer').remove()
      document.querySelector('#help').style.display = 'block'
      document.querySelector('#close').style.display = 'none'
      setTimeout(function(){ document.querySelector('#help').style.pointerEvents = 'auto' }, 1000);
      document.querySelector('#help').style.pointerEvents = 'none'
    },
    showAbout: function () {
      document.querySelector('#content').style.visibility = 'visible'
        document.querySelector('#help').style.display = 'none'
        document.querySelector('#close').style.display = 'block'
      if (document.getElementsByClassName('dimmer').length === 0) {
        var elemDiv = document.createElement('div')
        elemDiv.className = 'dimmer'
        document.body.append(elemDiv)
        document.querySelector('#content').style.visibility = 'visible'
        document.querySelector('div.dimmer').addEventListener('mouseover', function () {
          document.querySelector('#content').style.visibility = 'hidden'
          document.querySelector('#help').style.display = 'block'
          document.querySelector('#close').style.display = 'none'
          document.querySelector('div.dimmer').remove()
        })
      } else {
        document.querySelector('div.dimmer').remove()
      }
    // dim background
    }
  }
//   mounted () {
//     var Position = window.innerWidth / 2 - $('#about_matrix').width() / 2
//     Position = Position + 'px'
//     $('#about_matrix').css({
//       left: Position
//     })
//   }
}
</script>

<style scoped>
#close{
    display: none;
    border-radius: 50%;
    background-color: #f0f8ff;
    width: calc(10px + .8vw);
    height: calc(10px + .8vw);
    font-size: calc(10px + .4vw);
    margin: 5px 0px;
    line-height: initial;
}

#close:hover{
  background-color:#E9A45B;
  color: white;
}

#about_matrix{
    align-items: center;
    justify-content: center;
    margin-left: 12px;
    margin-top: 15px;
    margin-bottom: 15px;
}

@media only screen
  and (min-width : 100px)
  and (max-width : 700px) {
    #about_matrix{
    margin-left: calc(32px + 0.8vw);
  }
}

#title{
    display: inline-flex;
    z-index: 5;
    position: relative;
    align-items: center;
    justify-content: center;
    border-radius: 5em;
    background: #999999;
    padding: 2px calc(5px + 0.4vw);
}

#content{
    display: block;
    position: absolute;
    z-index: 4;
    visibility: hidden;
    align-items: center;
    text-align: left;
    justify-content: center;
    border-radius: 2em;
    background: #DEDEDE;
    top: 10px;
    padding: 50px calc(20px + 0.4vw) 20px calc(20px + 0.4vw);
    width: fit-content;
    margin-left: 25%;
    margin-right: 30%;
}

#Orgname{
    color: #fff;
    font-size: calc(9px + .9vw);
    font-weight: 700;
    padding: 0 1vw;
    margin: 0;
}

#matches{
    font-size: calc(10px + 0.4vw);
}

#help{
    border-radius: 50%;
    background-color: #f0f8ff;
    width: calc(10px + .8vw);
    height: calc(10px + .8vw);
    font-size: calc(10px + .4vw);
    margin: 0px 0px 0px 5px;
    line-height: initial;
}

/* iPhone SE */
@media only screen
  and (min-width : 200px)
  and (max-height : 600px) {
    #Orgname{
    font-size: calc(8px + 0.5vw);
  }
  #matches {
    font-size: calc(7px + 0.5vw);
  }
}
/* .x{
    position: relative;
    left: 50px;
    margin-top: -40px;
} */
</style>
